trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  azureSubscription: 'your-azure-subscription'
  webAppName: 'your-nextjs-app-name'
  resourceGroupName: 'your-resource-group'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Next.js App'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build Next.js app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/nextjs-app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nextjs-build'